import bcrypt from "bcryptjs";
import {
  db,
  usersTable,
  postsTable,
  circlesTable,
  pitchesTable,
  markersTable,
} from "@workspace/db";
import { logger } from "./logger";

export async function seedIfEmpty(): Promise<void> {
  const existing = await db.select().from(usersTable).limit(1);
  if (existing.length > 0) {
    logger.info("Seed: skipping (data present)");
    return;
  }
  logger.info("Seed: inserting initial dataset");

  const demoHash = await bcrypt.hash("oasis123", 10);

  await db.insert(usersTable).values([
    {
      id: "u_me",
      handle: "alex",
      name: "Alex Rivera",
      title: "Founder & CEO",
      company: "Helix Labs",
      city: "San Francisco",
      country: "USA",
      avatarKey: "avatar1",
      verified: true,
      followersCount: 12480,
      bio: "Building autonomous wet labs. Synthetic biology operator. SF.",
      passwordHash: demoHash,
    },
    {
      id: "u_amelia",
      handle: "ameliac",
      name: "Amelia Chen",
      title: "Partner",
      company: "North Bay Ventures",
      city: "New York",
      country: "USA",
      avatarKey: "avatar2",
      verified: true,
      followersCount: 38210,
      bio: "Series B+ vertical AI. Backing operators with shipped product.",
    },
    {
      id: "u_marcus",
      handle: "marcusv",
      name: "Marcus Vale",
      title: "Designer in Residence",
      company: "Atelier Nord",
      city: "Berlin",
      country: "Germany",
      avatarKey: "avatar3",
      verified: false,
      followersCount: 4870,
      bio: "Heirloom-grade product design. Studio in Mitte.",
    },
    {
      id: "u_priya",
      handle: "priya",
      name: "Priya Anand",
      title: "Head of Growth",
      company: "Ledger Cloud",
      city: "Bengaluru",
      country: "India",
      avatarKey: "avatar1",
      verified: true,
      followersCount: 9210,
      bio: "Replacing legacy ERPs. Hiring infra PMs.",
    },
    {
      id: "u_jonas",
      handle: "jonash",
      name: "Jonas Holm",
      title: "Engineer",
      company: "Polaris Robotics",
      city: "Stockholm",
      country: "Sweden",
      avatarKey: "avatar2",
      verified: false,
      followersCount: 1390,
      bio: "Warehouse-scale robotics. We retrofit, not replace.",
    },
  ]);

  await db.insert(postsTable).values([
    {
      id: "p1",
      authorId: "u_amelia",
      text: "We just closed our $42M Series B for vertical AI in commercial real estate. Looking to back two more pre-seed teams this quarter — operators only, no decks under 5 slides.",
      likesCount: 1284,
      retweetsCount: 312,
      commentsCount: 87,
      tipsTotal: 41,
      category: "investors",
    },
    {
      id: "p2",
      authorId: "u_marcus",
      text: "Studio update: the prototype shipped to manufacturing this morning. Every curve was hand-tuned in three weeks of late nights. Sometimes the brief is the easy part.",
      imageKey: "post1",
      likesCount: 642,
      retweetsCount: 71,
      commentsCount: 38,
      tipsTotal: 12,
      category: "general",
    },
    {
      id: "p_sponsored",
      authorId: "u_priya",
      text: "Ledger Cloud — the audit-ready ledger for Series A and beyond. Replace QuickBooks in a weekend. First 90 days free for HumanVerse founders.",
      imageKey: "post2",
      sponsored: true,
      sponsorLabel: "Promoted by Ledger Cloud",
      likesCount: 211,
      retweetsCount: 18,
      commentsCount: 9,
      tipsTotal: 0,
      category: "sponsored",
    },
    {
      id: "p3",
      authorId: "u_jonas",
      text: "Hot take: most hardware startups don't have a hardware problem. They have a story problem. The robot is fine. The narrative is mush.",
      likesCount: 388,
      retweetsCount: 92,
      commentsCount: 54,
      tipsTotal: 7,
      category: "general",
    },
    {
      id: "p4",
      authorId: "u_priya",
      text: "Hiring two senior PMs in Bengaluru and one staff PM in remote Europe. DM if you've shipped infra to >10k devs. Salary band on profile.",
      likesCount: 502,
      retweetsCount: 144,
      commentsCount: 28,
      tipsTotal: 3,
      category: "hiring",
    },
  ]);

  await db.insert(circlesTable).values([
    {
      id: "c1",
      name: "Founders Roundtable",
      about: "Closed-door operator chats: hiring, fundraising, hard calls.",
      category: "Operators",
      color: "#D4AF7A",
      coverKey: "post1",
      paid: true,
      price: 49,
      membersCount: 1284,
      activeNow: 47,
      founderIds: ["u_amelia", "u_priya"],
    },
    {
      id: "c2",
      name: "Climate Capital",
      about: "Investors and founders building the energy transition.",
      category: "Climate",
      color: "#48BB78",
      coverKey: "post2",
      paid: false,
      price: 0,
      membersCount: 612,
      activeNow: 22,
      founderIds: ["u_amelia"],
    },
    {
      id: "c3",
      name: "Design Engineers",
      about: "Where craft meets product. Critique nights every Thursday.",
      category: "Craft",
      color: "#6FA8DC",
      paid: false,
      price: 0,
      membersCount: 2104,
      activeNow: 88,
      founderIds: ["u_marcus"],
    },
    {
      id: "c4",
      name: "Family Office Briefing",
      about: "Curated deal flow for single-family offices. Application required.",
      category: "Capital",
      color: "#9D7BFF",
      paid: true,
      price: 199,
      membersCount: 184,
      activeNow: 12,
      founderIds: ["u_amelia"],
    },
    {
      id: "c5",
      name: "AI in Healthcare",
      about: "Clinicians, researchers, and founders shipping FDA-grade AI.",
      category: "Health",
      color: "#E5484D",
      paid: false,
      price: 0,
      membersCount: 942,
      activeNow: 31,
      founderIds: ["u_priya", "u_jonas"],
    },
  ]);

  await db.insert(pitchesTable).values([
    {
      id: "pi1",
      founderId: "u_me",
      title: "Helix — autonomous lab for synthetic biology",
      stage: "Seed",
      industry: "BioTech",
      raising: 4_000_000,
      raised: 2_650_000,
      city: "San Francisco",
      summary:
        "End-to-end robotic wet lab that runs experiments 24/7. We've cut iteration time from weeks to hours for three pilot customers.",
      coverKey: "post1",
      backersCount: 14,
      trending: true,
    },
    {
      id: "pi2",
      founderId: "u_jonas",
      title: "Polaris — ruggedized warehouse robotics",
      stage: "Series A",
      industry: "Robotics",
      raising: 18_000_000,
      raised: 11_400_000,
      city: "Stockholm",
      summary:
        "Forklift-scale robots that retrofit existing warehouses in 48 hours. $4.2M ARR, 90% gross margin.",
      coverKey: "post2",
      backersCount: 9,
      trending: false,
    },
    {
      id: "pi3",
      founderId: "u_marcus",
      title: "Atelier Nord — bespoke furniture marketplace",
      stage: "Pre-seed",
      industry: "Commerce",
      raising: 800_000,
      raised: 320_000,
      city: "Berlin",
      summary:
        "Heirloom-grade pieces from 40 European workshops. Built a waitlist of 2,200 collectors before launch.",
      backersCount: 6,
      trending: true,
    },
    {
      id: "pi4",
      founderId: "u_priya",
      title: "Ledger Cloud — modern accounting ledger",
      stage: "Series B",
      industry: "FinTech",
      raising: 30_000_000,
      raised: 30_000_000,
      city: "Bengaluru",
      summary:
        "Audit-ready ledger replacing legacy ERPs. 4,800 customers, 142% NRR.",
      backersCount: 22,
      trending: false,
    },
  ]);

  await db.insert(markersTable).values([
    { id: "m1", type: "person", label: "Amelia Chen", city: "New York", x: 0.27, y: 0.34, meta: "Partner · NBV", refId: "u_amelia" },
    { id: "m2", type: "business", label: "Helix Labs", city: "San Francisco", x: 0.16, y: 0.36, meta: "BioTech · Hiring", refId: "pi1" },
    { id: "m3", type: "project", label: "Polaris", city: "Stockholm", x: 0.52, y: 0.22, meta: "Series A · Trending", refId: "pi2" },
    { id: "m4", type: "person", label: "Marcus Vale", city: "Berlin", x: 0.51, y: 0.28, meta: "Designer in Residence", refId: "u_marcus" },
    { id: "m5", type: "business", label: "Atelier Nord", city: "Berlin", x: 0.515, y: 0.295, meta: "Commerce · 2.2k waitlist", refId: "pi3" },
    { id: "m6", type: "person", label: "Priya Anand", city: "Bengaluru", x: 0.69, y: 0.49, meta: "Head of Growth", refId: "u_priya" },
    { id: "m7", type: "project", label: "Ledger Cloud", city: "Bengaluru", x: 0.695, y: 0.5, meta: "Series B · Live", refId: "pi4" },
    { id: "m8", type: "business", label: "Sightglass Roasters", city: "São Paulo", x: 0.34, y: 0.66, meta: "F&B · Sponsor", refId: null },
    { id: "m9", type: "person", label: "Yuki Tanaka", city: "Tokyo", x: 0.84, y: 0.4, meta: "Robotics PM", refId: null },
    { id: "m10", type: "project", label: "Reef OS", city: "Sydney", x: 0.88, y: 0.74, meta: "Climate · Pre-seed", refId: null },
    { id: "m11", type: "business", label: "Lagos Studio", city: "Lagos", x: 0.5, y: 0.55, meta: "Creative · Hiring", refId: null },
    { id: "m12", type: "person", label: "Sara Bennani", city: "Casablanca", x: 0.46, y: 0.42, meta: "Investor", refId: null },
  ]);

  logger.info("Seed: complete");
}
